server:
  port: 0

spring:
  application:
    name: authentication

user:
  service-url: lb://USER

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: false   # no usar IP
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  issuer: veterinaria-auth
  expirationSeconds: 3600
  refreshExpirationSeconds: 604800

