server:
  port: 8091

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: false
          routes:

            # === USER SERVICE ===
            - id: user-service
              uri: lb://USER
              predicates:
                - Path=/gateway-service/api/user-service/**, /gateway-service/public/api/user-service/**
              filters:
                - StripPrefix=1

            # === PERSON SERVICE ===
            - id: person-service
              uri: lb://PERSON
              predicates:
                - Path=/gateway-service/api/person-service/**, /gateway-service/public/api/person-service/**
              filters:
                - StripPrefix=1

            # === PET SERVICE ===
            - id: pet-service
              uri: lb://PET
              predicates:
                - Path=/gateway-service/api/pet-service/**
              filters:
                - StripPrefix=1
            # === PET SERVICE ===
            - id: product-service
              uri: lb://PRODUCTS
              predicates:
                - Path=/gateway-service/api/product-service/**
              filters:
               - StripPrefix=1
            # === AUTH SERVICE ===
            - id: authentication-service
              uri: lb://AUTHENTICATION
              predicates:
                - Path=/gateway-service/api/authentication-service/**
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

jwt:
  publicKeyPem: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZp7u4tXzFhYkKqjFz1pkz7hZkz9ZQhQn0p6jZQyQh7ZkXz9Qh7Zkz9ZQhQn0p6jZQyQh7ZkXz9Qh7Zkz9ZQhQn0p6jZQyQh7ZkXz9Qh7Zkz9ZQhQn0p6jZQyQh7ZkXz9Qh7Zkz9ZQhQn0p6jZQyQh7ZkXz9Qh7Zkz9ZQhQn0p6jZQyQh7ZkXz9Qh7Zkz9ZQIDAQAB-----END PUBLIC KEY-----