spring:
  application:
    name: pet
  datasource:
    url: jdbc:mysql://mysql-barberia.alwaysdata.net:3306/barberia_veterinaria?useSSL=false&serverTimezone=UTC
    username: barberia_aux
    password: Ccva1007*
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    discovery:
      client:
        simple:
          local:
            host:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false   # no usar IP
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}

external-api:
  person:
    # noinspection SpringBootApplicationYaml
    service-url: lb://PERSON